// Next's static-image module declarations (`import photo from "./photo.jpg"`) normally
// arrive via next-env.d.ts. That file is generated by `next dev`/`next build` and is
// gitignored on Next's own guidance, so it does not exist on a fresh CI checkout — where
// `npm run typecheck` runs *before* the build step that would create it. Referencing the
// types directly keeps static image imports resolvable independently of build order.
/// <reference types="next/image-types/global" />
